type User {
    id: ID!
    username: String!
    roles: [String!]!
    fullName: String!
    email: String!
    phone: String
    status: String!
    createdAt: String!
    updatedAt: String!
}

type Bitacora {
    id: ID!
    titulo: String
    idProyecto: String!
    contexto: String
    error: String
    solucion: String
    fecha: String
    tags: [String]
    visible: Boolean
}

type Procedure {
    id: ID!
    titulo: String
    descripcion: String
    departamento: String
    tags: [String]
    isDeleted: Boolean
    isVisible: Boolean
    createdAt: String
    updatedAt: String
}

type Project {
    id: String
    code: String
    name: String
    departamentOrganisme: String
    gestorResponsableSolucio: String
    responsableProjecte: String
    equipDesenvolupament: String
    equipProjectesInfra: String
    equipProves: String
    equipAdminExplotacioXarxes: String
    oficinaSeguretat: String
    equipQualitat: String
    equipAdminOperacions: String
    equipAdminExplotacioSistemes: String
    gestorIntegracioSolucions: String
    createdAt: String
}

type Formacion {
    id: ID!
    name: String
    link: String
    description: String
    tags: [String]
    location: String
    visible: Boolean
    deleted: Boolean
    deletedAt: String
}

type Query {
    hello: String

    # USERS
    allUsers: [User]!

    # BITACORA
    allBitacoras: [Bitacora]!
    bitacoraById(id: ID!): Bitacora
    bitacorasByProject(idProyecto: String!): [Bitacora]!
    searchBitacoraByContexto(texto: String!): [Bitacora]!
    searchBitacoraByTexto(texto: String!): [Bitacora]!

    # PROCEDURES
    allProcedures: [Procedure]!
    procedureById(id: ID!): Procedure
    searchProceduresByTitulo(titulo: String!): [Procedure]!

    # PROJECTS
    getAllProjects: [Project]!
    getProjectById(id: String!): Project
    searchProjectsByName(name: String!): [Project]!

    # FORMACION 
    getAllFormaciones: [Formacion]
    searchFormacionByName(name: String!): [Formacion]
}

type Mutation {
  createProcedure(procedure: ProcedureInput!): Procedure
  updateProcedure(id: ID!, procedure: ProcedureInput!): Procedure
  softDeleteProcedure(id: String!): Boolean
  deleteProcedurePhysical(id: String!): Boolean

  createProject(project: ProjectInput!): Project
  updateProject(id: String!, project: ProjectInput!): Project
  deleteProjectPhysical(id: String!): Boolean
  softDeleteProject(id: String!): Boolean

  createBitacora(bitacora: BitacoraInput!): Bitacora
  updateBitacora(id: ID!, bitacora: BitacoraInput!): Bitacora
  softDeleteBitacora(id: String!): Boolean
  deleteBitacoraPhysical(id: String!): Boolean

  createFormacion(formacion: FormacionInput!): Formacion
  updateFormacion(id: ID!, formacion: FormacionInput!): Formacion
  deleteFormacion(id: ID!): Formacion
}

input ProcedureInput {
  titulo: String
  descripcion: String
  departamento: String
  tags: [String]
  visible: Boolean
}

input ProjectInput {
  code: String
  name: String
  departamentOrganisme: String
  gestorResponsableSolucio: String
  responsableProjecte: String
  equipDesenvolupament: String
  equipProjectesInfra: String
  equipProves: String
  equipAdminExplotacioXarxes: String
  oficinaSeguretat: String
  equipQualitat: String
  equipAdminOperacions: String
  equipAdminExplotacioSistemes: String
  gestorIntegracioSolucions: String
}

input BitacoraInput {
  idProyecto: String
  titulo: String
  contexto: String
  error: String
  solucion: String
  fecha: String
  tags: [String]
  visible: Boolean
}

input FormacionInput {
    name: String
    link: String
    description: String
    tags: [String]
    location: String
    visible: Boolean
}

